# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a0ab8c7b497049eff51971bc1204544e01c5a2943e15af67b24c4fce9f07b7314f6143bd92fd6565b147bf11120eb239df87fc19dd65d08fbc403e4287d0f7cf

test:
  secret_key_base: 3b9f082d4e99b690c883b6daa815264770686d6f782253d8af4e7b8c4fd2b5c33090eb8caf05793480eeb108ddadb7445de626093b77a09d81a84d0824c01c24

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
